### ISSUE TITLE
Improve the .git directory detection

### ISSUE THREAD

**Issue by Sweetchuck** [BernardoSilva/git-hooks-installer-plugin#1]
It is absolutely not sure the `.git` file system entry is a directory. It also can be a text file which contains the path of the real `.git` directory.
[--git-dir=&lt;path&gt;](https://git-scm.com/docs/git)

Bare repositories (mostly remotes) use more often hooks than the local repositories. A bare repository has no working-copy therefore no need to separate the git meta-data. So it has no `.git` directory.

I think the proper way to get the location of the .git directory is `git rev-parse --git-dir`. It returns `.` in case of a bare repository.
This hard-coded `'.git/hooks'` not a bullet proof solution. [Code](https://github.com/BernardoSilva/git-hooks-installer-plugin/blob/fe412a869590f042d1ac2e70e7767d088a874592/src/GitHooksInstallerPlugin/Composer/Installer.php#L61)

This package is a very good tool. :+1:

**Comment by BernardoSilva** [comment]
Hi @Sweetchuck , 

Good point you got there.
Can you explain me how to reproduce that use case?

I've tried with something like:
```sh
git --git-dir=./my-git-path
```

But does not seam to work... 
Can you explain me hoe to change a git repository to have a different .git dir?

Cheers,
Benny

**Comment by Sweetchuck** [comment]
* git init https://git-scm.com/docs/git-init#git-init---separate-git-dirltgitdirgt
* git clone https://git-scm.com/docs/git-clone#git-clone---separate-git-dirltgitdirgt

`git init  --separate-git-dir=/path/my/dir`

**Comment by BernardoSilva** [comment]
Hi @Sweetchuck ,

What do you think about this solution https://github.com/BernardoSilva/git-hooks-installer-plugin/pull/5 

Hope this improvement covers your use case.

Any other suggestion just let me know :)

Cheers,
Benny
