### ISSUE TITLE
does not support more than one plugin and overwrites data

### ISSUE THREAD

**Issue by glensc** [BernardoSilva/git-hooks-installer-plugin#2]
while this is simple implementation and satisfies your needs, found it not usable for general purpose.

i looked at [the implementation](
https://github.com/BernardoSilva/git-hooks-installer-plugin/blob/a07b872ea38b5008bde98ef8ed07ffb5ceab6397/src/GitHooksInstallerPlugin/Composer/Installer.php#L39-L54) and it just overrides install path to be `.git/hooks` (which is elegant, btw).

as a result the content of single `git-hook` type package is installed into `.git/hooks`, replacing whatever content is there. this is dangerous (one may lose existing hooks), and not mentioned in README.

```
➔ git init
Initialized empty Git repository in .git/

➔ install /etc/passwd .git/hooks/pre-commit

➔ ls -ld .git/hooks/pre-commit
-rwxr-xr-x 1 glen glen 2865 sept  10 23:00 .git/hooks/pre-commit*

➔ composer require bernardosilva/git-hooks-php --dev
Using version ^1.0 for bernardosilva/git-hooks-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing bernardosilva/git-hooks-installer-plugin (1.0.0): Loading from cache
  - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
  - Installing bernardosilva/git-hooks-php (1.0.0): Loading from cache
Writing lock file
Generating autoload files

➔ ls -l .git/hooks/
total 16
-rw-rw-r-- 1 glen glen  639 mai   10  2016 composer.json
-rw-rw-r-- 1 glen glen 1080 mai   10  2016 LICENSE
-rwxr-xr-x 1 glen glen 1616 mai   10  2016 pre-commit*
-rw-rw-r-- 1 glen glen 1010 mai   10  2016 README.md
➔

```

also, as already guessed, such solution is not suitable for multiple plugins (your README does speak in plural, leaving glues  that multiple packages are possible). 

i took the list of dependent packages from [packagist](https://packagist.org/packages/bernardosilva/git-hooks-installer-plugin/dependents), so i don't have to create package to show concept and installed second one (luckily there was one, and even same hook type `pre-commit`):

```
➔ composer require partnermarketing/pm-git-hooks-php --dev
Using version ^1.0 for partnermarketing/pm-git-hooks-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing partnermarketing/pm-git-hooks-php (1.0.0): Loading from cache
Writing lock file
Generating autoload files

➔ ls -l .git/hooks/
total 16
-rw-rw-r-- 1 glen glen  674 mai   10  2016 composer.json
-rw-rw-r-- 1 glen glen 1080 mai   10  2016 LICENSE
-rwxr-xr-x 1 glen glen 1616 mai   10  2016 pre-commit*
-rw-rw-r-- 1 glen glen 1010 mai   10  2016 README.md

➔ grep name .git/hooks/composer.json
    "name": "partnermarketing/pm-git-hooks-php",
        {"name": "Bernardo Silva", "email": "benny.stuff@gmail.com"}

➔

```

as you can see, it replaced whole `.git/hooks` content again, with the "latest installed" package of `git-hook` type.

ps: as you can see from my commands, this kind of packages should be installed with ` --dev`, so in production mode such hooks and their dependencies do not get installed. for example you don't want cs-fixer being installed in production, but having `bernardosilva/git-hooks-php` example present in `require`, not `require-dev` would make `squizlabs/php_codesniffer` being installed.

**Comment by BernardoSilva** [comment]
Hi @glensc ,

Thank you a lot for your feedback.
Really good points.

When I built it I just wanted to solve the problem on my company and make something that other people could adopt as well to enforce some kind of standards in a easy way.
Loads of open source projects could use something like this... :) 


I've made some changes to prevent it from deleting all the files in git hooks.
Can you check if this solves the problems you where mentioning?
See my PR: https://github.com/BernardoSilva/git-hooks-installer-plugin/pull/3

Is there anything else you would like to see improved related to this?


Cheers
